[book]
title = "Jamsession"
authors = ["Niko Matsakis"]
language = "en"
src = "md"

[preprocessor.anchor]
command = "mdbook-ezanchor"
scan-dirs = ["src"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 0
